config/routes.rb
Rails.application.routes.draw do
  resources :comments

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :locations do
  	resources :comments
  	resource :like, module: :locations
  end
  root to: 'visitors#index'
  devise_for :users
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :location
  validates_presence_of :location_id, :user_id
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :location
end

app/models/location.rb
class Location < ActiveRecord::Base
	geocoded_by :address

	after_validation :geocode, :if => :address_changed?
	validates_presence_of :latitude, :longitude

	has_many :comments
	has_many :likes
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_many :likes

  def likes?(location)
  	location.likes.where(user_id: id).any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_location

  def new
    @location = Location.new
    @comment = @location.comments.new
  end

  def create
    @comment = @location.comments.build(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    if @comment.save
      respond_to do |format|
        format.html { redirect_to @location }
        format.js
      end
    else
      redirect_to @location
      flash[:error] = "You cannot submit blank data"
    end
  end

  def edit
    @comment = @location.comments.find(params[:id])
  end

  def update
      @comment = @location.comments.find(params[:id])
      if @comment.user_id == current_user.id
        @comment.update(comment_params)
          redirect_to @plocation
      else
        redirect_to @location
        flash[:alert] = "You are not the correct user"
      end
  end

  def destroy
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end

    def set_location
      @location = Location.find(params[:location_id])
    end

end

app/controllers/locations/likes_controller.rb
class Locations::LikesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_location

	def create
		@location.likes.where(user_id: current_user.id).first_or_create
		respond_to do |format|
			format.html {redirect_to @location}
			format.js
		end
	end

	def destroy
		@location.likes.where(user_id: current_user.id).destroy_all
		respond_to do |format|
			format.html {redirect_to @location}
			format.js
		end
	end

	private

	def set_location
		@location = Location.find(params[:location_id])
	end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  def index
    @locations = Location.all
  end


  def show
    @hash = Gmaps4rails.build_markers(@location) do |location, marker|
      marker.lat location.latitude
      marker.lng location.longitude
      marker.infowindow "<a target='blank' href='https://www.google.com/maps/place/"+"#{location.address}"+"'>Get Directions With Google Maps</a>"
      marker.json({ title: location.name })
    end
  end


  def new
    @location = Location.new
  end


  def edit
  end


  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search_medical
    @location = params[:search]
    @distance = params[:miles]
    @medical = Medical.near(@location, @distance)

    if @location.empty?
      flash[:notice] = "You can't search without a search term; please enter a location and retry!"
      redirect_to root_url
    else
      if @medical.length < 1
        flash[:notice] = "Sorry! We couldn't find any farms within #{@distance} miles of #{@location}."
        redirect_to root_url
      else
        search_map(@medical)
      end
    end

  end

  private
    def set_location
      @location = Location.find(params[:id])
    end

    def location_params
      params.require(:location).permit(:address, :latitiude, :longitude, :name, :hours_open)
    end

    def search_map(medical)
      @medical = medical
        @hash = Gmaps4rails.build_markers(@medical) do |location, marker|
        marker.lat location.latitude
        marker.lng location.longitude
        marker.infowindow "<a href='/location/"+"#{location.id}"+"'>#{location.name}, #{location.address}</a>"
        marker.json({ title: location.name, id: location.id })
      end
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/comments/_comment.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
  	<h3 class="panel-title"><%= link_to "#{comment.user.name}", "#" %> | <small>Posted <%= time_ago_in_words(comment.created_at) %> ago</small>
		<% if comment.created_at != comment.updated_at %>
    		<small>| Edited <%= time_ago_in_words(comment.updated_at) %> ago</small>
  		<% end %>
  		<small>
  			<% if comment.user == current_user %>| <%= link_to "Edit", edit_location_comment_path(comment.location, comment ) %>
  			<% end %>
  		</small>		
  	</h3>
  	<div class="panel-body"><%= simple_format(comment.content) %></div>
	</div>

app/views/comments/_form.html.erb
<div class="comment_area">
  <%= form_for([@location, @location.comments.build]) do |f| %>
    <%= f.text_area :content, class: "form-control", rows: 6, placeholder: "Add A Comment..." %>
    <%= f.submit "Reply", class: "btn btn-primary" %>

    <% end %>

</div>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/layouts/_footer.html.erb
<div class="container">
	<p class="text-muted">Assembled with Adderall, 3x Red Bulls, 3x Coffee and some Chips!</p>
</div>

app/views/layouts/_location_maps.html.erb
<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ 
	provider: { disableDefaultUI: true}, 
	internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(16);
});
</script>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav id="mainNav" class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'CPR Training', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li>
    <%= link_to 'About', page_path('about') %>
</li>
<li>
    <%= link_to 'Locations', locations_path, class: "page-scroll" %>
</li>

<% if user_signed_in? %>

<li> <%= link_to 'Edit Account', edit_user_registration_path %>
</li>
<li>
	<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
</li>

<% else %>

<li>
    <%= link_to 'Sign In', new_user_session_path %>
</li>
<li>
    <%= link_to 'Sign Up', new_user_registration_path %>
</li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Deploy" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Deploy" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div>
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Locations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/likes/_likes.html.erb
<% if user_signed_in? && current_user.likes?(@location) %>
<%= link_to "Unlike", location_like_path(@location), method: :delete, remote: true %>
<% else %>
<%= link_to "Like", location_like_path(@location), method: :post, remote: true %>
<% end %>

<%= @location.likes.count %>

app/views/locations/likes/create.js.erb
$("#likes").html("<%=j render partial: "locations/likes/likes" %>");

app/views/locations/likes/destroy.js.erb
$("#likes").html("<%=j render partial: "locations/likes/likes" %>");

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<div style='width: 100%;'>
  <div id="map" style='width: 100%; height: 400px;'></div>
  <%= render 'layouts/location_maps' %>
</div>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

<div class="cpr_center_info">
	<h1><%= @location.name %></h1>
	<h3><%= @location.address %></h3>
</div>

	<div class="likes">
		<%= render partial: "locations/likes/likes" %>
	</div>
</div>

<div class="user_comments">
      <%= render @location.comments %>
      <% if user_signed_in? %>
        <%= render "comments/form" %>
      <% end %>
</div>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
Assembled with Love
</p>

app/views/visitors/index.html.erb
<header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1>Get the Training to Save A Life</h1>
                <hr>
                <p>Find a training center, schedule an appointment. Rate your experience to improve it for the next person who gets trained!</p>
                <a href="#about" class="btn btn-primary btn-xl page-scroll">Sign Up</a>
            </div>
        </div>
    </header>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Locations</h2>
                    <hr class="light">
                    <p class="text-faded">See the locations near you</p>
                    <a href="#" class="btn btn-default btn-xl">Go!</a>
                </div>
            </div>
        </div>
    </section>